version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      DB_USERNAME: auth_app
      DB_PASSWORD: password
      DB_DATABASE: auth_db
      DB_HOST: localhost
      JWT_SECRET: M69PE25Ht6JE2A
      JWT_EXPIRES_IN: 604800
    depends_on:
      - backend
    ports:
      - "3000:3000"
    links:
      - "backend:be"

# version: '3'
# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     image: frontend
#     depends_on:
#       - backend
#     command:
#       - npm start
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '8000:8000'
#     image: backend
#     command:
#       - npm start


# version: '3'

# services:
#   db:
#     image: postgres
#     restart: always
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: auth_app
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: auth_db
#     ports:
#       - "5432:5432"

#   app:
#     build: .
#     environment:
#       PORT: 5000
#       DB_USERNAME: auth_app
#       DB_PASSWORD: password
#       DB_DATABASE: auth_db
#       DB_HOST: localhost
#       JWT_SECRET: M69PE25Ht6JE2A
#       JWT_EXPIRES_IN: 604800
#     depends_on:
#       - db
#     ports:
#       - "3000:3000"
