'use strict';

const faker = require('faker');

module.exports = {
  up: (queryInterface, Sequelize) => {

    return queryInterface.bulkInsert('Images', [
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3401403/pexels-photo-3401403.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/2245200/pexels-photo-2245200.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ridiculus mus mauris vitae ultricies leo integer. Rhoncus urna neque viverra justo. Imperdiet dui accumsan sit amet nulla facilisi. Tempus imperdiet nulla malesuada pellentesque elit. Consequat mauris nunc congue nisi vitae suscipit tellus. Amet mattis vulputate enim nulla aliquet porttitor. Imperdiet massa tincidunt nunc pulvinar sapien. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/2245194/pexels-photo-2245194.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Amet mattis vulputate enim nulla aliquet porttitor. Imperdiet massa tincidunt nunc pulvinar sapien. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Aliquam eleifend mi in nulla. Arcu dictum varius duis at consectetur lorem donec. Donec enim diam vulputate ut pharetra sit amet aliquam. Tempus egestas sed sed risus pretium quam. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Blandit massa enim nec dui nunc mattis enim ut tellus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/7147599/pexels-photo-7147599.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3760958/pexels-photo-3760958.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ridiculus mus mauris vitae ultricies leo integer. Rhoncus urna neque viverra justo. Imperdiet dui accumsan sit amet nulla facilisi. Tempus imperdiet nulla malesuada pellentesque elit. Consequat mauris nunc congue nisi vitae suscipit tellus. Amet mattis vulputate enim nulla aliquet porttitor. Imperdiet massa tincidunt nunc pulvinar sapien. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3678057/pexels-photo-3678057.png?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Amet mattis vulputate enim nulla aliquet porttitor. Imperdiet massa tincidunt nunc pulvinar sapien. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Aliquam eleifend mi in nulla. Arcu dictum varius duis at consectetur lorem donec. Donec enim diam vulputate ut pharetra sit amet aliquam. Tempus egestas sed sed risus pretium quam. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Blandit massa enim nec dui nunc mattis enim ut tellus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/1394506/pexels-photo-1394506.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/824300/pexels-photo-824300.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Quam quisque id diam vel quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Elementum tempus egestas sed sed risus pretium quam vulputate. Id porta nibh venenatis cras sed felis. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Mattis rhoncus urna neque viverra justo nec ultrices.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6232046/pexels-photo-6232046.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Mattis rhoncus urna neque viverra justo nec ultrices. Duis at tellus at urna condimentum mattis pellentesque. Dolor purus non enim praesent elementum facilisis leo vel. Molestie nunc non blandit massa enim. Nisl purus in mollis nunc sed id semper risus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3637834/pexels-photo-3637834.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Tellus id interdum velit laoreet id. Non pulvinar neque laoreet suspendisse. Vitae nunc sed velit dignissim sodales ut eu sem integer. Placerat duis ultricies lacus sed turpis. Gravida rutrum quisque non tellus orci ac. Cursus euismod quis viverra nibh cras pulvinar mattis. Cras semper auctor neque vitae tempus quam pellentesque nec nam.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6231720/pexels-photo-6231720.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Tortor at auctor urna nunc id cursus metus aliquam eleifend. Ut diam quam nulla porttitor. Amet purus gravida quis blandit turpis cursus in hac habitasse. Sagittis nisl rhoncus mattis rhoncus urna neque. Faucibus interdum posuere lorem ipsum dolor sit. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Neque viverra justo nec ultrices dui.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6272310/pexels-photo-6272310.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Consectetur adipiscing elit pellentesque habitant morbi tristique. Sed libero enim sed faucibus turpis in eu mi bibendum. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Amet facilisis magna etiam tempor. Tellus id interdum velit laoreet id. Non pulvinar neque laoreet suspendisse.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6231809/pexels-photo-6231809.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Amet facilisis magna etiam tempor. Tellus id interdum velit laoreet id. Non pulvinar neque laoreet suspendisse. Vitae nunc sed velit dignissim sodales ut eu sem integer. Placerat duis ultricies lacus sed turpis. Gravida rutrum quisque non tellus orci ac. Cursus euismod quis viverra nibh cras pulvinar mattis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5529604/pexels-photo-5529604.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Gravida rutrum quisque non tellus orci ac. Cursus euismod quis viverra nibh cras pulvinar mattis. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Ut diam quam nulla porttitor. Amet purus gravida quis blandit turpis cursus in hac habitasse.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/7590931/pexels-photo-7590931.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Ut diam quam nulla porttitor. Amet purus gravida quis blandit turpis cursus in hac habitasse. Sagittis nisl rhoncus mattis rhoncus urna neque. Faucibus interdum posuere lorem ipsum dolor sit. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Neque viverra justo nec ultrices dui.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/1537638/pexels-photo-1537638.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Placerat duis ultricies lacus sed turpis. Gravida rutrum quisque non tellus orci ac. Cursus euismod quis viverra nibh cras pulvinar mattis. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Ut diam quam nulla porttitor. Amet purus gravida quis blandit turpis cursus in hac habitasse.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/609549/pexels-photo-609549.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Metus dictum at tempor commodo ullamcorper a. Rutrum quisque non tellus orci. Velit egestas dui id ornare arcu odio ut sem. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/8733921/pexels-photo-8733921.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Eget dolor morbi non arcu risus quis. Justo donec enim diam vulputate ut pharetra sit. Ac orci phasellus egestas tellus rutrum tellus. Vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3367459/pexels-photo-3367459.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Ac orci phasellus egestas tellus rutrum tellus. Vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit. Gravida neque convallis a cras semper auctor neque. Rhoncus est pellentesque elit ullamcorper. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tellus id interdum velit laoreet id donec.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/2147029/pexels-photo-2147029.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Sagittis id consectetur purus ut faucibus pulvinar. Etiam sit amet nisl purus in mollis nunc sed. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Metus dictum at tempor commodo ullamcorper a. Rutrum quisque non tellus orci.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/7969612/pexels-photo-7969612.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Velit egestas dui id ornare arcu odio ut sem. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Eget dolor morbi non arcu risus quis. Justo donec enim diam vulputate ut pharetra sit. Ac orci phasellus egestas tellus rutrum tellus. Vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/233129/pexels-photo-233129.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Rhoncus est pellentesque elit ullamcorper. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Tellus id interdum velit laoreet id donec. Ac turpis egestas integer eget aliquet. Donec ultrices tincidunt arcu non sodales neque sodales ut.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/2709385/pexels-photo-2709385.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eget dolor morbi non arcu risus quis. Justo donec enim diam vulputate ut pharetra sit. Ac orci phasellus egestas tellus rutrum tellus. Vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit. Gravida neque convallis a cras semper auctor neque. Rhoncus est pellentesque elit ullamcorper. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/1456951/pexels-photo-1456951.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Metus dictum at tempor commodo ullamcorper a. Rutrum quisque non tellus orci. Velit egestas dui id ornare arcu odio ut sem. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/4153135/pexels-photo-4153135.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Eget dolor morbi non arcu risus quis. Justo donec enim diam vulputate ut pharetra sit. Ac orci phasellus egestas tellus rutrum tellus. Vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit. Gravida neque convallis a cras semper auctor neque.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5544127/pexels-photo-5544127.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Ac orci phasellus egestas tellus rutrum tellus. Vel turpis nunc eget lorem. Proin libero nunc consequat interdum varius sit. Gravida neque convallis a cras semper auctor neque. Rhoncus est pellentesque elit ullamcorper. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6816480/pexels-photo-6816480.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Fringilla ut morbi tincidunt augue interdum velit. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas dui id ornare arcu odio ut sem nulla. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/7500637/pexels-photo-7500637.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Fringilla ut morbi tincidunt augue interdum velit.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3856033/pexels-photo-3856033.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Augue mauris augue neque gravida in fermentum et sollicitudin ac. Fringilla ut morbi tincidunt augue interdum velit. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas dui id ornare arcu odio ut sem nulla. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Rhoncus mattis rhoncus urna neque viverra justo.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6646917/pexels-photo-6646917.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Fringilla ut morbi tincidunt augue interdum velit. Accumsan lacus vel facilisis volutpat est velit egestas dui id. Egestas dui id ornare arcu odio ut sem nulla. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Rhoncus mattis rhoncus urna neque viverra justo. At consectetur lorem donec massa. Nulla pharetra diam sit amet nisl. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/4180324/pexels-photo-4180324.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Nulla pharetra diam sit amet nisl. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Euismod nisi porta lorem mollis. Arcu cursus euismod quis viverra nibh cras pulvinar. Ante in nibh mauris cursus. Enim praesent elementum facilisis leo vel fringilla est.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/2305003/pexels-photo-2305003.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Arcu dictum varius duis at consectetur lorem donec massa sapien. Ipsum a arcu cursus vitae congue. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Amet consectetur adipiscing elit pellentesque habitant morbi. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Est sit amet facilisis magna etiam tempor orci eu lobortis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/2078248/pexels-photo-2078248.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Amet consectetur adipiscing elit pellentesque habitant morbi. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Est sit amet facilisis magna etiam tempor orci eu lobortis. Facilisi morbi tempus iaculis urna id volutpat lacus. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat in egestas erat imperdiet sed euismod nisi porta lorem.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/1689899/pexels-photo-1689899.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat in egestas erat imperdiet sed euismod nisi porta lorem. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Dignissim cras tincidunt lobortis feugiat vivamus at. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/730061/pexels-photo-730061.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Placerat in egestas erat imperdiet sed euismod nisi porta lorem. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Dignissim cras tincidunt lobortis feugiat vivamus at. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Lorem ipsum dolor sit amet consectetur adipiscing. Lorem mollis aliquam ut porttitor leo.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3283193/pexels-photo-3283193.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Est sit amet facilisis magna etiam tempor orci eu lobortis. Facilisi morbi tempus iaculis urna id volutpat lacus. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat in egestas erat imperdiet sed euismod nisi porta lorem. Penatibus et magnis dis parturient montes nascetur ridiculus mus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/7238627/pexels-photo-7238627.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Est sit amet facilisis magna etiam tempor orci eu lobortis. Facilisi morbi tempus iaculis urna id volutpat lacus. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Placerat in egestas erat imperdiet sed euismod nisi porta lorem.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/260898/pexels-photo-260898.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Dignissim cras tincidunt lobortis feugiat vivamus at. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Lorem ipsum dolor sit amet consectetur adipiscing. Lorem mollis aliquam ut porttitor leo.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5745780/pexels-photo-5745780.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor orci dapibus ultrices in iaculis. Arcu dictum varius duis at consectetur lorem donec massa sapien. Ipsum a arcu cursus vitae congue. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Amet consectetur adipiscing elit pellentesque habitant morbi.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/2977382/pexels-photo-2977382.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eget nunc scelerisque viverra mauris in aliquam sem. Amet facilisis magna etiam tempor orci eu lobortis. Dictumst vestibulum rhoncus est pellentesque. Magna etiam tempor orci eu lobortis. Massa enim nec dui nunc mattis. Nulla aliquet enim tortor at auctor urna nunc. Volutpat odio facilisis mauris sit amet massa vitae. Eleifend quam adipiscing vitae proin sagittis. Condimentum lacinia quis vel eros donec ac odio tempor orci. Porttitor eget dolor morbi non arcu risus quis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/994807/pexels-photo-994807.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Eget nunc scelerisque viverra mauris in aliquam sem. Amet facilisis magna etiam tempor orci eu lobortis. Dictumst vestibulum rhoncus est pellentesque. Magna etiam tempor orci eu lobortis. Massa enim nec dui nunc mattis. Nulla aliquet enim tortor at auctor urna nunc.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1682751/pexels-photo-1682751.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Magna etiam tempor orci eu lobortis. Massa enim nec dui nunc mattis. Nulla aliquet enim tortor at auctor urna nunc. Volutpat odio facilisis mauris sit amet massa vitae. Eleifend quam adipiscing vitae proin sagittis. Condimentum lacinia quis vel eros donec ac odio tempor orci. Porttitor eget dolor morbi non arcu risus quis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1565521/pexels-photo-1565521.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Vitae turpis massa sed elementum tempus egestas. Consectetur purus ut faucibus pulvinar elementum. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Neque ornare aenean euismod elementum nisi quis eleifend. Sit amet est placerat in egestas erat imperdiet sed euismod. Varius sit amet mattis vulputate enim nulla aliquet porttitor.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5275476/pexels-photo-5275476.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Consectetur purus ut faucibus pulvinar elementum. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Neque ornare aenean euismod elementum nisi quis eleifend. Sit amet est placerat in egestas erat imperdiet sed euismod. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Cum sociis natoque penatibus et magnis dis parturient montes.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/907158/pexels-photo-907158.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Varius sit amet mattis vulputate enim nulla aliquet porttitor. Cum sociis natoque penatibus et magnis dis parturient montes. Velit ut tortor pretium viverra. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Blandit turpis cursus in hac habitasse platea dictumst. Purus sit amet volutpat consequat mauris nunc.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/3038786/pexels-photo-3038786.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Sit amet est placerat in egestas erat imperdiet sed euismod. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Cum sociis natoque penatibus et magnis dis parturient montes. Velit ut tortor pretium viverra. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Blandit turpis cursus in hac habitasse platea dictumst.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5275515/pexels-photo-5275515.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eget gravida cum sociis natoque penatibus et magnis dis parturient. Blandit turpis cursus in hac habitasse platea dictumst. Purus sit amet volutpat consequat mauris nunc. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Enim facilisis gravida neque convallis a cras semper.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5275475/pexels-photo-5275475.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Neque ornare aenean euismod elementum nisi quis eleifend. Sit amet est placerat in egestas erat imperdiet sed euismod. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Cum sociis natoque penatibus et magnis dis parturient montes. Velit ut tortor pretium viverra. Eget gravida cum sociis natoque penatibus et magnis dis parturient.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/3355047/pexels-photo-3355047.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Vitae turpis massa sed elementum tempus egestas. Consectetur purus ut faucibus pulvinar elementum. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Neque ornare aenean euismod elementum nisi quis eleifend. Sit amet est placerat in egestas erat imperdiet sed euismod. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Cum sociis natoque penatibus et magnis dis parturient montes.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5745814/pexels-photo-5745814.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eget gravida cum sociis natoque penatibus et magnis dis parturient. Blandit turpis cursus in hac habitasse platea dictumst. Purus sit amet volutpat consequat mauris nunc. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Enim facilisis gravida neque convallis a cras semper.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/3856020/pexels-photo-3856020.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Pulvinar mattis nunc sed blandit libero volutpat sed cras. Facilisis mauris sit amet massa vitae tortor. Aliquet bibendum enim facilisis gravida neque convallis a. Aliquet nibh praesent tristique magna sit. Faucibus scelerisque eleifend donec pretium vulputate. Fames ac turpis egestas integer eget aliquet nibh.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/725910/pexels-photo-725910.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Facilisis mauris sit amet massa vitae tortor. Aliquet bibendum enim facilisis gravida neque convallis a. Aliquet nibh praesent tristique magna sit. Faucibus scelerisque eleifend donec pretium vulputate. Fames ac turpis egestas integer eget aliquet nibh. Amet nulla facilisi morbi tempus iaculis urna. Pulvinar mattis nunc sed blandit libero.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/4593431/pexels-photo-4593431.png?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eu volutpat odio facilisis mauris sit amet massa vitae. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Facilisis mauris sit amet massa vitae tortor. Aliquet bibendum enim facilisis gravida neque convallis a. Aliquet nibh praesent tristique magna sit. Faucibus scelerisque eleifend donec pretium vulputate.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/159935/pexels-photo-159935.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Aliquet nibh praesent tristique magna sit. Faucibus scelerisque eleifend donec pretium vulputate. Fames ac turpis egestas integer eget aliquet nibh. Amet nulla facilisi morbi tempus iaculis urna. Pulvinar mattis nunc sed blandit libero. Sit amet venenatis urna cursus. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Sociis natoque penatibus et magnis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5205307/pexels-photo-5205307.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu volutpat odio facilisis mauris sit amet massa vitae. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Facilisis mauris sit amet massa vitae tortor. Aliquet bibendum enim facilisis gravida neque convallis a. Aliquet nibh praesent tristique magna sit.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/3856023/pexels-photo-3856023.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Facilisis mauris sit amet massa vitae tortor. Aliquet bibendum enim facilisis gravida neque convallis a. Aliquet nibh praesent tristique magna sit. Faucibus scelerisque eleifend donec pretium vulputate. Fames ac turpis egestas integer eget aliquet nibh. Amet nulla facilisi morbi tempus iaculis urna. Pulvinar mattis nunc sed blandit libero.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5909695/pexels-photo-5909695.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Fames ac turpis egestas integer eget aliquet nibh. Amet nulla facilisi morbi tempus iaculis urna. Pulvinar mattis nunc sed blandit libero. Sit amet venenatis urna cursus. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Sociis natoque penatibus et magnis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5872476/pexels-photo-5872476.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Massa tincidunt dui ut ornare lectus. Eget arcu dictum varius duis at consectetur lorem. Sed id semper risus in hendrerit. Dolor magna eget est lorem ipsum dolor sit. Sit amet dictum sit amet. Habitant morbi tristique senectus et netus. Ornare suspendisse sed nisi lacus sed viverra. Augue lacus viverra vitae congue eu consequat ac.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6128987/pexels-photo-6128987.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Egestas maecenas pharetra convallis posuere morbi. Id diam maecenas ultricies mi eget mauris pharetra et. Massa tincidunt dui ut ornare lectus. Eget arcu dictum varius duis at consectetur lorem. Sed id semper risus in hendrerit. Dolor magna eget est lorem ipsum dolor sit. Sit amet dictum sit amet. Habitant morbi tristique senectus et netus. Ornare suspendisse sed nisi lacus sed viverra.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/2526935/pexels-photo-2526935.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Eget arcu dictum varius duis at consectetur lorem. Sed id semper risus in hendrerit. Dolor magna eget est lorem ipsum dolor sit. Sit amet dictum sit amet. Habitant morbi tristique senectus et netus. Ornare suspendisse sed nisi lacus sed viverra. Augue lacus viverra vitae congue eu consequat ac.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/5721327/pexels-photo-5721327.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas maecenas pharetra convallis posuere morbi. Id diam maecenas ultricies mi eget mauris pharetra et. Massa tincidunt dui ut ornare lectus. Eget arcu dictum varius duis at consectetur lorem. Sed id semper risus in hendrerit.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/50709/thailand-buddhists-monks-and-50709.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Sed id semper risus in hendrerit. Dolor magna eget est lorem ipsum dolor sit. Sit amet dictum sit amet. Habitant morbi tristique senectus et netus. Ornare suspendisse sed nisi lacus sed viverra. Augue lacus viverra vitae congue eu consequat ac.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6038297/pexels-photo-6038297.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/2128042/pexels-photo-2128042.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Posuere morbi leo urna molestie at elementum eu. Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6624965/pexels-photo-6624965.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/315191/pexels-photo-315191.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/4274876/pexels-photo-4274876.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/8752656/pexels-photo-8752656.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Posuere morbi leo urna molestie at elementum eu. Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://www.pexels.com/photo/black-woman-creating-earthenware-on-street-of-village-3760974/",
        description: "Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6567714/pexels-photo-6567714.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1199605/pexels-photo-1199605.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/2989625/pexels-photo-2989625.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie at elementum eu. Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1437614/pexels-photo-1437614.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/4185875/pexels-photo-4185875.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/372281/pexels-photo-372281.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Posuere morbi leo urna molestie at elementum eu. Adipiscing enim eu turpis egestas. Duis ut diam quam nulla porttitor massa id neque. Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/3243020/pexels-photo-3243020.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/933624/pexels-photo-933624.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/2354073/pexels-photo-2354073.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Varius duis at consectetur lorem donec massa. Orci phasellus egestas tellus rutrum tellus. Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/7293100/pexels-photo-7293100.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Id nibh tortor id aliquet lectus proin nibh nisl condimentum. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum. Ut eu sem integer vitae. Fringilla urna porttitor rhoncus dolor purus non. Aenean et tortor at risus viverra adipiscing.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1117808/pexels-photo-1117808.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Nisi scelerisque eu ultrices vitae auctor eu augue. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1153976/pexels-photo-1153976.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Tellus id interdum velit laoreet id donec. Nisi scelerisque eu ultrices vitae auctor eu augue. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6561125/pexels-photo-6561125.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/757828/pexels-photo-757828.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/7277590/pexels-photo-7277590.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/784707/pexels-photo-784707.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1186116/pexels-photo-1186116.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/667200/pexels-photo-667200.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Mattis enim ut tellus elementum sagittis vitae et. Leo urna molestie at elementum eu. Neque viverra justo nec ultrices dui sapien eget mi.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/235731/pexels-photo-235731.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Mattis enim ut tellus elementum sagittis vitae et. Leo urna molestie at elementum eu. Neque viverra justo nec ultrices dui sapien eget mi.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/974320/pexels-photo-974320.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/1313814/pexels-photo-1313814.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Nisi scelerisque eu ultrices vitae auctor eu augue. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6907093/pexels-photo-6907093.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Mattis enim ut tellus elementum sagittis vitae et. Leo urna molestie at elementum eu. Neque viverra justo nec ultrices dui sapien eget mi.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 2,
        imageUrl: "https://images.pexels.com/photos/6836476/pexels-photo-6836476.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Mattis enim ut tellus elementum sagittis vitae et.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5029879/pexels-photo-5029879.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Tellus id interdum velit laoreet id donec. Nisi scelerisque eu ultrices vitae auctor eu augue. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5910062/pexels-photo-5910062.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Odio eu feugiat pretium nibh ipsum consequat nisl vel. Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5909876/pexels-photo-5909876.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5954956/pexels-photo-5954956.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Mattis enim ut tellus elementum sagittis vitae et. Leo urna molestie at elementum eu. Neque viverra justo nec ultrices dui sapien eget mi.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/4483669/pexels-photo-4483669.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5871874/pexels-photo-5871874.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Turpis egestas integer eget aliquet. Est sit amet facilisis magna etiam tempor orci eu lobortis. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Mattis enim ut tellus elementum sagittis vitae et. Leo urna molestie at elementum eu. Neque viverra justo nec ultrices dui sapien eget mi.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5874244/pexels-photo-5874244.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Massa enim nec dui nunc. Sapien pellentesque habitant morbi tristique senectus. Arcu non sodales neque sodales ut etiam sit. Ut faucibus pulvinar elementum integer enim neque volutpat. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Turpis egestas integer eget aliquet.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6463292/pexels-photo-6463292.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Tempor id eu nisl nunc. Risus ultricies tristique nulla aliquet enim. Enim eu turpis egestas pretium aenean. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Tellus in metus vulputate eu scelerisque felis. Varius duis at consectetur lorem. Facilisis gravida neque convallis a. Aenean et tortor at risus viverra adipiscing at in tellus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/5847668/pexels-photo-5847668.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Sed elementum tempus egestas sed sed risus pretium. A scelerisque purus semper eget duis at. Tempor id eu nisl nunc. Risus ultricies tristique nulla aliquet enim. Enim eu turpis egestas pretium aenean. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Tellus in metus vulputate eu scelerisque felis.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/6331570/pexels-photo-6331570.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed elementum tempus egestas sed sed risus pretium. A scelerisque purus semper eget duis at. Tempor id eu nisl nunc. Risus ultricies tristique nulla aliquet enim. Enim eu turpis egestas pretium aenean.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/4296723/pexels-photo-4296723.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Enim eu turpis egestas pretium aenean. Scelerisque eleifend donec pretium vulputate sapien nec sagittis. Tellus in metus vulputate eu scelerisque felis. Varius duis at consectetur lorem. Facilisis gravida neque convallis a. Aenean et tortor at risus viverra adipiscing at in tellus. Libero volutpat sed cras ornare arcu dui vivamus.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: faker.commerce.productName(),
        userId: 1,
        imageUrl: "https://images.pexels.com/photos/3885021/pexels-photo-3885021.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
        description: "Facilisis gravida neque convallis a. Aenean et tortor at risus viverra adipiscing at in tellus. Libero volutpat sed cras ornare arcu dui vivamus. Congue eu consequat ac felis donec et odio pellentesque. Sapien et ligula ullamcorper malesuada proin. Et sollicitudin ac orci phasellus egestas tellus rutrum. Lorem dolor sed viverra ipsum.",
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ], {});

  },

  down: (queryInterface, Sequelize) => {

    return queryInterface.bulkDelete('Images', null, {});

  }
};
